<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="minibot">

  <!-- chassis -->
  <xacro:property name="length" value="0.17" />
  <xacro:property name="width"  value="0.079" />
  <xacro:property name="height" value="0.051" />

  <!-- main PCB board on top -->
  <xacro:property name="PCBlength" value="0.17" />
  <xacro:property name="PCBwidth"  value="0.126" />
  <xacro:property name="PCBheight" value="0.004" />

  <!-- IMU board BNO055 (mounted) -->
  <xacro:property name="IMUlength" value="0.020" />
  <xacro:property name="IMUwidth"  value="0.027" />
  <xacro:property name="IMUheight" value="0.010" />

  <!-- Raspberry Pi (mounted) -->
  <xacro:property name="IMUlength" value="0.085" />
  <xacro:property name="IMUwidth"  value="0.056" />
  <xacro:property name="IMUheight" value="0.030" />

  <!-- Hokuyo laser rangefinder - base -->
  <xacro:property name="laserLength" value="0.05" />
  <xacro:property name="laserWidth"  value="0.05" />
  <xacro:property name="laserHeight" value="0.041" />
  <!-- Hokuyo laser rangefinder - cylinder -->
  <xacro:property name="laserCylLength" value="0.0265" />
  <xacro:property name="laserCylRadius" value="0.0375" />

  <!-- wheel depth is 2.35 cm overall with rubber -->
  <xacro:property name="wheellength" value="0.0235" />
  <xacro:property name="wheelradius" value="0.025" />

  <!-- Materials -->
  <material name="silver">
    <color rgba="0.75 0.75 0.75 1"/>
  </material>
  <material name="blue">
    <color rgba="0 0 0.8 1"/>
  </material>
  <material name="black">
    <color rgba="0 0 0 1"/>
  </material>
  <material name="white">
    <color rgba="1 1 1 1"/>
  </material>
  <!-- #B9 A7 76 = 185 167 118 -->
  <material name="euroPCB">
    <color rgba="0.73 0.65 0.46 1"/>
  </material>

  <!-- Default Inertial -->
  <xacro:macro name="default_inertial" params="mass">
    <inertial>
      <mass value="${mass}" />
      <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
    </inertial>
  </xacro:macro>

  <!--
  The chassis.
  "base_link" is a more common name for a chassis in ROS.
  -->
  <link name="base_link">
    <visual>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
      <!-- ORIGIN OF THE BASE?!?     <origin rpy="0 0 0" xyz="0 0 0.03"/> -->
      <material name="silver"/>
    </visual>
    <collision>
      <geometry>
        <box size="${length} ${width} ${height}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- the main PCB on top of the chassis, where everything is mounted -->
  <link name="mainPCB">
    <visual>
      <geometry>
        <box size="${PCBlength} ${PCBwidth} ${PCBheight}"/>
      </geometry>
      <!-- Located on top of the base -->
      <origin rpy="0 0 0" xyz="0 0 -${height/2}"/>
      <material name="euroPCB"/>
    </visual>
    <collision>
      <geometry>
        <box size="${PCBlength} ${PCBwidth} ${PCBheight}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- the IMU on the main PCB -->
  <link name="IMU">
    <visual>
      <geometry>
        <box size="${IMUlength} ${IMUwidth} ${IMUheight}"/>
      </geometry>
      <!-- Located on top of the base, on top of the PCB -->
      <origin rpy="0 0 0" xyz="0 0 -${(height/2)+PCBwidth}"/>
      <material name="Blue"/>
    </visual>
    <collision>
      <geometry>
        <box size="${IMUlength} ${IMUwidth} ${IMUheight}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- Wheel 1 -->
  <link name="wheel_1">
    <visual>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
      <!--
      origin roll,pitch,yaw and x,y,z
      1. We rotate the wheel by PI/2 around the Y axis (pitch)
      2. We move the origin +5.65 cm (11.3 cm/2) to the front (+x)
      and +3.95 cm (7.9cm/2) to the left of the center (+y)
      and -0.65 cm (3cm - 2,35cm) down from the center (-z).
    -->
    <origin rpy="0 ${pi/2} ${pi/2}" xyz="0.0565 0.0395 -0.0065"/>
    <material name="black"/>
  </visual>
  <collision>
    <geometry>
      <cylinder length="${wheellength}" radius="${wheelradius}"/>
    </geometry>
  </collision>
  <xacro:default_inertial mass="1"/>
  </link>

  <!-- Wheel 2 -->
  <link name="wheel_2">
    <visual>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${pi/2}" xyz="-0.0565 0.0395 -0.0065"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- Wheel 3 -->
  <link name="wheel_3">
    <visual>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${pi/2}" xyz="0.0565 -0.0395 -0.0065"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- Wheel 4 -->
  <link name="wheel_4">
    <visual>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
      <origin rpy="0 ${pi/2} ${pi/2}" xyz="-0.0565 -0.0395 -0.0065"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <cylinder length="${wheellength}" radius="${wheelradius}"/>
      </geometry>
    </collision>
    <xacro:default_inertial mass="1"/>
  </link>

  <!-- Joint for wheel 1 -->
  <joint name="base_to_wheel1" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_1"/>
    <origin xyz="0 0 0"/>
  </joint>
  <!-- Joint for wheel 2 -->
  <joint name="base_to_wheel2" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_2"/>
    <origin xyz="0 0 0"/>
  </joint>
  <!-- Joint for wheel 3 -->
  <joint name="base_to_wheel3" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_3"/>
    <origin xyz="0 0 0"/>
  </joint>
  <!-- Joint for wheel 4 -->
  <joint name="base_to_wheel4" type="fixed">
    <parent link="base_link"/>
    <child link="wheel_4"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- Joint for mainPCB -->
  <joint name="base_to_mainPCB" type="fixed">
    <parent link="base_link"/>
    <child link="mainPCB"/>
    <origin xyz="0 0 0"/>
  </joint>

  <!-- Joint for IMU -->
  <joint name="base_to_IMU" type="fixed">
    <parent link="base_link"/>
    <child link="IMU"/>
    <origin xyz="0 0 0"/>
  </joint>

</robot>
